### ISSUE TITLE
Simple Icons Request

### ISSUE THREAD

**Issue by jglamp** [BabylonJS/Branding-Toolkit#6]
Howdy!

Just reaching out from [Simple Icons](https://github.com/simple-icons/simple-icons/tree/develop) about including your logo in our set for embedding. Your license says that you allow free distribution of the logo without changes, however, we need to make a monochrome version of the logo. Do we have permission to either use a provided monochrome logo or make one based off the original Babylon.JS logo in this repo for our project?

**Comment by RaananW** [comment]
We have no issue whatsoever with you making the changes to the logo. I am checking if we can change the license on the entire repo, but if this approval is enough for you, please feel free to use it
